{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a98030af-fcd1-4d63-a36e-38ba053498fa",
   "metadata": {},
   "source": [
    "# A full business solution\n",
    "\n",
    "\n",
    "### BUSINESS CHALLENGE:\n",
    "\n",
    "Create a product that builds a Brochure for a company to be used for prospective clients, investors and potential recruits.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d5b08506-dc8b-4443-9201-5f1848161363",
   "metadata": {},
   "outputs": [],
   "source": [
    "# imports\n",
    "# If these fail, please check you're running from an 'activated' environment with (llms) in the command prompt\n",
    "\n",
    "import os\n",
    "import requests\n",
    "import json\n",
    "from typing import List\n",
    "from dotenv import load_dotenv\n",
    "from bs4 import BeautifulSoup\n",
    "from IPython.display import Markdown, display, update_display\n",
    "from openai import OpenAI"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "fc5d8880-f2ee-4c06-af16-ecbc0262af61",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "API key looks good so far\n"
     ]
    }
   ],
   "source": [
    "# Initialize and constants\n",
    "\n",
    "load_dotenv()\n",
    "api_key = os.getenv('OPENAI_API_KEY')\n",
    "\n",
    "if api_key and api_key.startswith('sk-proj-') and len(api_key)>10:\n",
    "    print(\"API key looks good so far\")\n",
    "else:\n",
    "    print(\"There might be a problem with your API key? Please visit the troubleshooting notebook!\")\n",
    "    \n",
    "MODEL = 'gpt-4o-mini'\n",
    "openai = OpenAI()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "106dd65e-90af-4ca8-86b6-23a41840645b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# A class to represent a Webpage\n",
    "\n",
    "class Website:\n",
    "    \"\"\"\n",
    "    A utility class to represent a Website that we have scraped, now with links\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, url):\n",
    "        self.url = url\n",
    "        response = requests.get(url)\n",
    "        self.body = response.content\n",
    "        soup = BeautifulSoup(self.body, 'html.parser')\n",
    "        self.title = soup.title.string if soup.title else \"No title found\"\n",
    "        if soup.body:\n",
    "            for irrelevant in soup.body([\"script\", \"style\", \"img\", \"input\"]):\n",
    "                irrelevant.decompose()\n",
    "            self.text = soup.body.get_text(separator=\"\\n\", strip=True)\n",
    "        else:\n",
    "            self.text = \"\"\n",
    "        links = [link.get('href') for link in soup.find_all('a')]\n",
    "        self.links = [link for link in links if link]\n",
    "\n",
    "    def get_contents(self):\n",
    "        return f\"Webpage Title:\\n{self.title}\\nWebpage Contents:\\n{self.text}\\n\\n\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "e30d8128-933b-44cc-81c8-ab4c9d86589a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['https://edwarddonner.com/',\n",
       " 'https://edwarddonner.com/outsmart/',\n",
       " 'https://edwarddonner.com/about-me-and-about-nebula/',\n",
       " 'https://edwarddonner.com/posts/',\n",
       " 'https://edwarddonner.com/',\n",
       " 'https://news.ycombinator.com',\n",
       " 'https://nebula.io/?utm_source=ed&utm_medium=referral',\n",
       " 'https://www.prnewswire.com/news-releases/wynden-stark-group-acquires-nyc-venture-backed-tech-startup-untapt-301269512.html',\n",
       " 'https://patents.google.com/patent/US20210049536A1/',\n",
       " 'https://www.linkedin.com/in/eddonner/',\n",
       " 'https://edwarddonner.com/2024/11/13/llm-engineering-resources/',\n",
       " 'https://edwarddonner.com/2024/11/13/llm-engineering-resources/',\n",
       " 'https://edwarddonner.com/2024/10/16/from-software-engineer-to-ai-data-scientist-resources/',\n",
       " 'https://edwarddonner.com/2024/10/16/from-software-engineer-to-ai-data-scientist-resources/',\n",
       " 'https://edwarddonner.com/2024/08/06/outsmart/',\n",
       " 'https://edwarddonner.com/2024/08/06/outsmart/',\n",
       " 'https://edwarddonner.com/2024/06/26/choosing-the-right-llm-resources/',\n",
       " 'https://edwarddonner.com/2024/06/26/choosing-the-right-llm-resources/',\n",
       " 'https://edwarddonner.com/',\n",
       " 'https://edwarddonner.com/outsmart/',\n",
       " 'https://edwarddonner.com/about-me-and-about-nebula/',\n",
       " 'https://edwarddonner.com/posts/',\n",
       " 'mailto:hello@mygroovydomain.com',\n",
       " 'https://www.linkedin.com/in/eddonner/',\n",
       " 'https://twitter.com/edwarddonner',\n",
       " 'https://www.facebook.com/edward.donner.52']"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ed = Website(\"https://edwarddonner.com\")\n",
    "ed.links"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1771af9c-717a-4fca-bbbe-8a95893312c3",
   "metadata": {},
   "source": [
    "## First step: Have GPT-4o-mini figure out which links are relevant\n",
    "\n",
    "### Use a call to gpt-4o-mini to read the links on a webpage, and respond in structured JSON.  \n",
    "It should decide which links are relevant, and replace relative links such as \"/about\" with \"https://company.com/about\".  \n",
    "We will use \"one shot prompting\" in which we provide an example of how it should respond in the prompt.\n",
    "\n",
    "This is an excellent use case for an LLM, because it requires nuanced understanding. Imagine trying to code this without LLMs by parsing and analyzing the webpage - it would be very hard!\n",
    "\n",
    "Sidenote: there is a more advanced technique called \"Structured Outputs\" in which we require the model to respond according to a spec. We cover this technique in Week 8 during our autonomous Agentic AI project."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "6957b079-0d96-45f7-a26a-3487510e9b35",
   "metadata": {},
   "outputs": [],
   "source": [
    "link_system_prompt = \"You are provided with a list of links found on a webpage. \\\n",
    "You are able to decide which of the links would be most relevant to include in a brochure about the company, \\\n",
    "such as links to an About page, or a Company page, or Careers/Jobs pages.\\n\"\n",
    "link_system_prompt += \"You should respond in JSON as in this example:\"\n",
    "link_system_prompt += \"\"\"\n",
    "{\n",
    "    \"links\": [\n",
    "        {\"type\": \"about page\", \"url\": \"https://full.url/goes/here/about\"},\n",
    "        {\"type\": \"careers page\": \"url\": \"https://another.full.url/careers\"}\n",
    "    ]\n",
    "}\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "b97e4068-97ed-4120-beae-c42105e4d59a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "You are provided with a list of links found on a webpage. You are able to decide which of the links would be most relevant to include in a brochure about the company, such as links to an About page, or a Company page, or Careers/Jobs pages.\n",
      "You should respond in JSON as in this example:\n",
      "{\n",
      "    \"links\": [\n",
      "        {\"type\": \"about page\", \"url\": \"https://full.url/goes/here/about\"},\n",
      "        {\"type\": \"careers page\": \"url\": \"https://another.full.url/careers\"}\n",
      "    ]\n",
      "}\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print(link_system_prompt)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "8e1f601b-2eaf-499d-b6b8-c99050c9d6b3",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_links_user_prompt(website):\n",
    "    user_prompt = f\"Here is the list of links on the website of {website.url} - \"\n",
    "    user_prompt += \"please decide which of these are relevant web links for a brochure about the company, respond with the full https URL in JSON format. \\\n",
    "Do not include Terms of Service, Privacy, email links.\\n\"\n",
    "    user_prompt += \"Links (some might be relative links):\\n\"\n",
    "    user_prompt += \"\\n\".join(website.links)\n",
    "    return user_prompt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "6bcbfa78-6395-4685-b92c-22d592050fd7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Here is the list of links on the website of https://edwarddonner.com - please decide which of these are relevant web links for a brochure about the company, respond with the full https URL in JSON format. Do not include Terms of Service, Privacy, email links.\n",
      "Links (some might be relative links):\n",
      "https://edwarddonner.com/\n",
      "https://edwarddonner.com/outsmart/\n",
      "https://edwarddonner.com/about-me-and-about-nebula/\n",
      "https://edwarddonner.com/posts/\n",
      "https://edwarddonner.com/\n",
      "https://news.ycombinator.com\n",
      "https://nebula.io/?utm_source=ed&utm_medium=referral\n",
      "https://www.prnewswire.com/news-releases/wynden-stark-group-acquires-nyc-venture-backed-tech-startup-untapt-301269512.html\n",
      "https://patents.google.com/patent/US20210049536A1/\n",
      "https://www.linkedin.com/in/eddonner/\n",
      "https://edwarddonner.com/2024/11/13/llm-engineering-resources/\n",
      "https://edwarddonner.com/2024/11/13/llm-engineering-resources/\n",
      "https://edwarddonner.com/2024/10/16/from-software-engineer-to-ai-data-scientist-resources/\n",
      "https://edwarddonner.com/2024/10/16/from-software-engineer-to-ai-data-scientist-resources/\n",
      "https://edwarddonner.com/2024/08/06/outsmart/\n",
      "https://edwarddonner.com/2024/08/06/outsmart/\n",
      "https://edwarddonner.com/2024/06/26/choosing-the-right-llm-resources/\n",
      "https://edwarddonner.com/2024/06/26/choosing-the-right-llm-resources/\n",
      "https://edwarddonner.com/\n",
      "https://edwarddonner.com/outsmart/\n",
      "https://edwarddonner.com/about-me-and-about-nebula/\n",
      "https://edwarddonner.com/posts/\n",
      "mailto:hello@mygroovydomain.com\n",
      "https://www.linkedin.com/in/eddonner/\n",
      "https://twitter.com/edwarddonner\n",
      "https://www.facebook.com/edward.donner.52\n"
     ]
    }
   ],
   "source": [
    "print(get_links_user_prompt(ed))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "a29aca19-ca13-471c-a4b4-5abbfa813f69",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_links(url):\n",
    "    website = Website(url)\n",
    "    response = openai.chat.completions.create(\n",
    "        model=MODEL,\n",
    "        messages=[\n",
    "            {\"role\": \"system\", \"content\": link_system_prompt},\n",
    "            {\"role\": \"user\", \"content\": get_links_user_prompt(website)}\n",
    "      ],\n",
    "        response_format={\"type\": \"json_object\"}\n",
    "    )\n",
    "    result = response.choices[0].message.content\n",
    "    return json.loads(result)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "74a827a0-2782-4ae5-b210-4a242a8b4cc2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['/',\n",
       " '/models',\n",
       " '/datasets',\n",
       " '/spaces',\n",
       " '/posts',\n",
       " '/docs',\n",
       " '/enterprise',\n",
       " '/pricing',\n",
       " '/login',\n",
       " '/join',\n",
       " '/meta-llama/Llama-3.3-70B-Instruct',\n",
       " '/tencent/HunyuanVideo',\n",
       " '/Datou1111/shou_xin',\n",
       " '/black-forest-labs/FLUX.1-dev',\n",
       " '/Qwen/QwQ-32B-Preview',\n",
       " '/models',\n",
       " '/spaces/JeffreyXiang/TRELLIS',\n",
       " '/spaces/ginipick/FLUXllama',\n",
       " '/spaces/multimodalart/flux-style-shaping',\n",
       " '/spaces/Kwai-Kolors/Kolors-Virtual-Try-On',\n",
       " '/spaces/Yuanshi/OminiControl',\n",
       " '/spaces',\n",
       " '/datasets/HuggingFaceFW/fineweb-2',\n",
       " '/datasets/fka/awesome-chatgpt-prompts',\n",
       " '/datasets/CohereForAI/Global-MMLU',\n",
       " '/datasets/O1-OPEN/OpenO1-SFT',\n",
       " '/datasets/amphora/QwQ-LongCoT-130K',\n",
       " '/datasets',\n",
       " '/join',\n",
       " '/pricing#endpoints',\n",
       " '/pricing#spaces',\n",
       " '/pricing',\n",
       " '/enterprise',\n",
       " '/enterprise',\n",
       " '/enterprise',\n",
       " '/enterprise',\n",
       " '/enterprise',\n",
       " '/enterprise',\n",
       " '/enterprise',\n",
       " '/allenai',\n",
       " '/facebook',\n",
       " '/amazon',\n",
       " '/google',\n",
       " '/Intel',\n",
       " '/microsoft',\n",
       " '/grammarly',\n",
       " '/Writer',\n",
       " '/docs/transformers',\n",
       " '/docs/diffusers',\n",
       " '/docs/safetensors',\n",
       " '/docs/huggingface_hub',\n",
       " '/docs/tokenizers',\n",
       " '/docs/peft',\n",
       " '/docs/transformers.js',\n",
       " '/docs/timm',\n",
       " '/docs/trl',\n",
       " '/docs/datasets',\n",
       " '/docs/text-generation-inference',\n",
       " '/docs/accelerate',\n",
       " '/models',\n",
       " '/datasets',\n",
       " '/spaces',\n",
       " '/tasks',\n",
       " 'https://ui.endpoints.huggingface.co',\n",
       " '/chat',\n",
       " '/huggingface',\n",
       " '/brand',\n",
       " '/terms-of-service',\n",
       " '/privacy',\n",
       " 'https://apply.workable.com/huggingface/',\n",
       " 'mailto:press@huggingface.co',\n",
       " '/learn',\n",
       " '/docs',\n",
       " '/blog',\n",
       " 'https://discuss.huggingface.co',\n",
       " 'https://status.huggingface.co/',\n",
       " 'https://github.com/huggingface',\n",
       " 'https://twitter.com/huggingface',\n",
       " 'https://www.linkedin.com/company/huggingface/',\n",
       " '/join/discord',\n",
       " 'https://www.zhihu.com/org/huggingface',\n",
       " 'https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/blog/chinese-language-blog/wechat.jpg']"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Anthropic has made their site harder to scrape, so I'm using HuggingFace..\n",
    "\n",
    "huggingface = Website(\"https://huggingface.co\")\n",
    "huggingface.links"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "d3d583e2-dcc4-40cc-9b28-1e8dbf402924",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'links': [{'type': 'about page', 'url': 'https://huggingface.co'},\n",
       "  {'type': 'careers page', 'url': 'https://apply.workable.com/huggingface/'},\n",
       "  {'type': 'enterprise page', 'url': 'https://huggingface.co/enterprise'},\n",
       "  {'type': 'pricing page', 'url': 'https://huggingface.co/pricing'},\n",
       "  {'type': 'blog page', 'url': 'https://huggingface.co/blog'},\n",
       "  {'type': 'community page', 'url': 'https://discuss.huggingface.co'},\n",
       "  {'type': 'GitHub page', 'url': 'https://github.com/huggingface'},\n",
       "  {'type': 'LinkedIn page',\n",
       "   'url': 'https://www.linkedin.com/company/huggingface/'},\n",
       "  {'type': 'Twitter page', 'url': 'https://twitter.com/huggingface'}]}"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "get_links(\"https://huggingface.co\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0d74128e-dfb6-47ec-9549-288b621c838c",
   "metadata": {},
   "source": [
    "## Second step: make the brochure!\n",
    "\n",
    "Assemble all the details into another prompt to GPT4-o"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "85a5b6e2-e7ef-44a9-bc7f-59ede71037b5",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_all_details(url):\n",
    "    result = \"Landing page:\\n\"\n",
    "    result += Website(url).get_contents()\n",
    "    links = get_links(url)\n",
    "    print(\"Found links:\", links)\n",
    "    for link in links[\"links\"]:\n",
    "        result += f\"\\n\\n{link['type']}\\n\"\n",
    "        result += Website(link[\"url\"]).get_contents()\n",
    "    return result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "5099bd14-076d-4745-baf3-dac08d8e5ab2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found links: {'links': [{'type': 'about page', 'url': 'https://huggingface.co/about'}, {'type': 'careers page', 'url': 'https://apply.workable.com/huggingface/'}, {'type': 'company page', 'url': 'https://huggingface.co/huggingface'}, {'type': 'blog page', 'url': 'https://huggingface.co/blog'}, {'type': 'enterprise page', 'url': 'https://huggingface.co/enterprise'}, {'type': 'pricing page', 'url': 'https://huggingface.co/pricing'}]}\n",
      "Landing page:\n",
      "Webpage Title:\n",
      "Hugging Face – The AI community building the future.\n",
      "Webpage Contents:\n",
      "Hugging Face\n",
      "Models\n",
      "Datasets\n",
      "Spaces\n",
      "Posts\n",
      "Docs\n",
      "Enterprise\n",
      "Pricing\n",
      "Log In\n",
      "Sign Up\n",
      "The AI community building the future.\n",
      "The platform where the machine learning community collaborates on models, datasets, and applications.\n",
      "Trending on\n",
      "this week\n",
      "Models\n",
      "meta-llama/Llama-3.3-70B-Instruct\n",
      "Updated\n",
      "3 days ago\n",
      "•\n",
      "102k\n",
      "•\n",
      "936\n",
      "tencent/HunyuanVideo\n",
      "Updated\n",
      "6 days ago\n",
      "•\n",
      "3.73k\n",
      "•\n",
      "978\n",
      "Datou1111/shou_xin\n",
      "Updated\n",
      "4 days ago\n",
      "•\n",
      "7.84k\n",
      "•\n",
      "273\n",
      "black-forest-labs/FLUX.1-dev\n",
      "Updated\n",
      "Aug 16\n",
      "•\n",
      "1.38M\n",
      "•\n",
      "7.22k\n",
      "Qwen/QwQ-32B-Preview\n",
      "Updated\n",
      "14 days ago\n",
      "•\n",
      "92.8k\n",
      "•\n",
      "1.26k\n",
      "Browse 400k+ models\n",
      "Spaces\n",
      "Running\n",
      "on\n",
      "Zero\n",
      "1.08k\n",
      "🏢\n",
      "TRELLIS\n",
      "Scalable and Versatile 3D Generation from images\n",
      "Running\n",
      "on\n",
      "Zero\n",
      "281\n",
      "🦀🏆\n",
      "FLUXllama\n",
      "FLUX 4-bit Quantization(just 8GB VRAM)\n",
      "Running\n",
      "on\n",
      "L40S\n",
      "225\n",
      "🚀\n",
      "Flux Style Shaping\n",
      "Optical illusions and style transfer with FLUX\n",
      "Running\n",
      "on\n",
      "CPU Upgrade\n",
      "5.91k\n",
      "👕\n",
      "Kolors Virtual Try-On\n",
      "Running\n",
      "on\n",
      "Zero\n",
      "478\n",
      "🌍\n",
      "OminiControl\n",
      "Browse 150k+ applications\n",
      "Datasets\n",
      "HuggingFaceFW/fineweb-2\n",
      "Updated\n",
      "5 days ago\n",
      "•\n",
      "21.1k\n",
      "•\n",
      "275\n",
      "fka/awesome-chatgpt-prompts\n",
      "Updated\n",
      "Sep 3\n",
      "•\n",
      "7.94k\n",
      "•\n",
      "6.51k\n",
      "CohereForAI/Global-MMLU\n",
      "Updated\n",
      "about 20 hours ago\n",
      "•\n",
      "3.67k\n",
      "•\n",
      "75\n",
      "O1-OPEN/OpenO1-SFT\n",
      "Updated\n",
      "21 days ago\n",
      "•\n",
      "1.27k\n",
      "•\n",
      "171\n",
      "amphora/QwQ-LongCoT-130K\n",
      "Updated\n",
      "8 days ago\n",
      "•\n",
      "433\n",
      "•\n",
      "44\n",
      "Browse 100k+ datasets\n",
      "The Home of Machine Learning\n",
      "Create, discover and collaborate on ML better.\n",
      "The collaboration platform\n",
      "Host and collaborate on unlimited public models, datasets and applications.\n",
      "Move faster\n",
      "With the HF Open source stack.\n",
      "Explore all modalities\n",
      "Text, image, video, audio or even 3D.\n",
      "Build your portfolio\n",
      "Share your work with the world and build your ML profile.\n",
      "Sign Up\n",
      "Accelerate your ML\n",
      "We provide paid Compute and Enterprise solutions.\n",
      "Compute\n",
      "Deploy on optimized\n",
      "Inference Endpoints\n",
      "or update your\n",
      "Spaces applications\n",
      "to a GPU in a few clicks.\n",
      "View pricing\n",
      "Starting at $0.60/hour for GPU\n",
      "Enterprise\n",
      "Give your team the most advanced platform to build AI with enterprise-grade security, access controls and\n",
      "\t\t\tdedicated support.\n",
      "Getting started\n",
      "Starting at $20/user/month\n",
      "Single Sign-On\n",
      "Regions\n",
      "Priority Support\n",
      "Audit Logs\n",
      "Resource Groups\n",
      "Private Datasets Viewer\n",
      "More than 50,000 organizations are using Hugging Face\n",
      "Ai2\n",
      "Enterprise\n",
      "non-profit\n",
      "•\n",
      "361 models\n",
      "•\n",
      "1.71k followers\n",
      "AI at Meta\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "2.05k models\n",
      "•\n",
      "3.74k followers\n",
      "Amazon Web Services\n",
      "company\n",
      "•\n",
      "21 models\n",
      "•\n",
      "2.41k followers\n",
      "Google\n",
      "company\n",
      "•\n",
      "910 models\n",
      "•\n",
      "5.44k followers\n",
      "Intel\n",
      "company\n",
      "•\n",
      "217 models\n",
      "•\n",
      "2.05k followers\n",
      "Microsoft\n",
      "company\n",
      "•\n",
      "351 models\n",
      "•\n",
      "6.03k followers\n",
      "Grammarly\n",
      "company\n",
      "•\n",
      "10 models\n",
      "•\n",
      "98 followers\n",
      "Writer\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "15 models\n",
      "•\n",
      "178 followers\n",
      "Our Open Source\n",
      "We are building the foundation of ML tooling with the community.\n",
      "Transformers\n",
      "136,226\n",
      "State-of-the-art ML for Pytorch, TensorFlow, and JAX.\n",
      "Diffusers\n",
      "26,619\n",
      "State-of-the-art diffusion models for image and audio generation in PyTorch.\n",
      "Safetensors\n",
      "2,950\n",
      "Simple, safe way to store and distribute neural networks weights safely and quickly.\n",
      "Hub Python Library\n",
      "2,165\n",
      "Client library for the HF Hub: manage repositories from your Python runtime.\n",
      "Tokenizers\n",
      "9,149\n",
      "Fast tokenizers, optimized for both research and production.\n",
      "PEFT\n",
      "16,695\n",
      "Parameter efficient finetuning methods for large models.\n",
      "Transformers.js\n",
      "12,336\n",
      "State-of-the-art Machine Learning for the web. Run Transformers directly in your browser, with no need for a server.\n",
      "timm\n",
      "32,588\n",
      "State-of-the-art computer vision models, layers, optimizers, training/evaluation, and utilities.\n",
      "TRL\n",
      "10,305\n",
      "Train transformer language models with reinforcement learning.\n",
      "Datasets\n",
      "19,348\n",
      "Access and share datasets for computer vision, audio, and NLP tasks.\n",
      "Text Generation Inference\n",
      "9,407\n",
      "Toolkit to serve Large Language Models.\n",
      "Accelerate\n",
      "8,049\n",
      "Easily train and use PyTorch models with multi-GPU, TPU, mixed-precision.\n",
      "Website\n",
      "Models\n",
      "Datasets\n",
      "Spaces\n",
      "Tasks\n",
      "Inference Endpoints\n",
      "HuggingChat\n",
      "Company\n",
      "About\n",
      "Brand assets\n",
      "Terms of service\n",
      "Privacy\n",
      "Jobs\n",
      "Press\n",
      "Resources\n",
      "Learn\n",
      "Documentation\n",
      "Blog\n",
      "Forum\n",
      "Service Status\n",
      "Social\n",
      "GitHub\n",
      "Twitter\n",
      "LinkedIn\n",
      "Discord\n",
      "Zhihu\n",
      "WeChat\n",
      "\n",
      "\n",
      "\n",
      "about page\n",
      "Webpage Title:\n",
      "about (Sergei)\n",
      "Webpage Contents:\n",
      "Hugging Face\n",
      "Models\n",
      "Datasets\n",
      "Spaces\n",
      "Posts\n",
      "Docs\n",
      "Enterprise\n",
      "Pricing\n",
      "Log In\n",
      "Sign Up\n",
      "Sergei\n",
      "about\n",
      "Follow\n",
      "selvivincent's profile picture\n",
      "Kalaipriya's profile picture\n",
      "Renumathi's profile picture\n",
      "3\n",
      "\t\t\t\t\tfollowers\n",
      "·\n",
      "0 following\n",
      "AI & ML interests\n",
      "None yet\n",
      "Organizations\n",
      "None yet\n",
      "models\n",
      "None public yet\n",
      "datasets\n",
      "None public yet\n",
      "Company\n",
      "© Hugging Face\n",
      "TOS\n",
      "Privacy\n",
      "About\n",
      "Jobs\n",
      "Website\n",
      "Models\n",
      "Datasets\n",
      "Spaces\n",
      "Pricing\n",
      "Docs\n",
      "\n",
      "\n",
      "\n",
      "careers page\n",
      "Webpage Title:\n",
      "Hugging Face - Current Openings\n",
      "Webpage Contents:\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "company page\n",
      "Webpage Title:\n",
      "huggingface (Hugging Face)\n",
      "Webpage Contents:\n",
      "Hugging Face\n",
      "Models\n",
      "Datasets\n",
      "Spaces\n",
      "Posts\n",
      "Docs\n",
      "Enterprise\n",
      "Pricing\n",
      "Log In\n",
      "Sign Up\n",
      "Hugging Face\n",
      "Enterprise\n",
      "company\n",
      "Verified\n",
      "https://huggingface.co\n",
      "huggingface\n",
      "huggingface\n",
      "Follow\n",
      "7,398\n",
      "AI & ML interests\n",
      "The AI community building the future.\n",
      "Team members\n",
      "224\n",
      "+190\n",
      "+177\n",
      "+156\n",
      "+146\n",
      "+126\n",
      "Organization Card\n",
      "Community\n",
      "About org cards\n",
      "👋 Hi!\n",
      "We are on a mission to democratize\n",
      "good\n",
      "machine learning, one commit at a time.\n",
      "If that sounds like something you should be doing, why don't you\n",
      "join us\n",
      "!\n",
      "For press enquiries, you can\n",
      "✉️ contact our team here\n",
      ".\n",
      "Collections\n",
      "1\n",
      "DistilBERT release\n",
      "Original DistilBERT model, checkpoints obtained from using teacher-student learning from the original BERT checkpoints.\n",
      "distilbert/distilbert-base-cased\n",
      "Fill-Mask\n",
      "•\n",
      "Updated\n",
      "May 6\n",
      "•\n",
      "402k\n",
      "•\n",
      "35\n",
      "distilbert/distilbert-base-uncased\n",
      "Fill-Mask\n",
      "•\n",
      "Updated\n",
      "May 6\n",
      "•\n",
      "15.6M\n",
      "•\n",
      "570\n",
      "distilbert/distilbert-base-multilingual-cased\n",
      "Fill-Mask\n",
      "•\n",
      "Updated\n",
      "May 6\n",
      "•\n",
      "513k\n",
      "•\n",
      "147\n",
      "distilbert/distilbert-base-uncased-finetuned-sst-2-english\n",
      "Text Classification\n",
      "•\n",
      "Updated\n",
      "Dec 19, 2023\n",
      "•\n",
      "9.7M\n",
      "•\n",
      "•\n",
      "641\n",
      "spaces\n",
      "23\n",
      "Sort: \n",
      "\t\tRecently updated\n",
      "Running\n",
      "284\n",
      "😻\n",
      "Open Source Ai Year In Review 2024\n",
      "What happened in open-source AI this year, and what’s next?\n",
      "Running\n",
      "193\n",
      "⚡\n",
      "paper-central\n",
      "Running\n",
      "42\n",
      "🔋\n",
      "Inference Playground\n",
      "Running\n",
      "19\n",
      "🏢\n",
      "Number Tokenization Blog\n",
      "Running\n",
      "on\n",
      "TPU v5e\n",
      "5\n",
      "💬\n",
      "Keras Chatbot Battle\n",
      "Running\n",
      "99\n",
      "⚡\n",
      "Modelcard Creator\n",
      "Expand 23\n",
      "\t\t\t\t\t\t\tspaces\n",
      "models\n",
      "16\n",
      "Sort: \n",
      "\t\tRecently updated\n",
      "huggingface/timesfm-tourism-monthly\n",
      "Updated\n",
      "4 days ago\n",
      "•\n",
      "23\n",
      "huggingface/CodeBERTa-language-id\n",
      "Text Classification\n",
      "•\n",
      "Updated\n",
      "Mar 29\n",
      "•\n",
      "513\n",
      "•\n",
      "54\n",
      "huggingface/falcon-40b-gptq\n",
      "Text Generation\n",
      "•\n",
      "Updated\n",
      "Jun 14, 2023\n",
      "•\n",
      "13\n",
      "•\n",
      "12\n",
      "huggingface/autoformer-tourism-monthly\n",
      "Updated\n",
      "May 24, 2023\n",
      "•\n",
      "1.82k\n",
      "•\n",
      "9\n",
      "huggingface/distilbert-base-uncased-finetuned-mnli\n",
      "Text Classification\n",
      "•\n",
      "Updated\n",
      "Mar 22, 2023\n",
      "•\n",
      "1.8k\n",
      "•\n",
      "2\n",
      "huggingface/informer-tourism-monthly\n",
      "Updated\n",
      "Feb 24, 2023\n",
      "•\n",
      "1.25k\n",
      "•\n",
      "5\n",
      "huggingface/time-series-transformer-tourism-monthly\n",
      "Updated\n",
      "Feb 23, 2023\n",
      "•\n",
      "2.22k\n",
      "•\n",
      "18\n",
      "huggingface/the-no-branch-repo\n",
      "Text-to-Image\n",
      "•\n",
      "Updated\n",
      "Feb 10, 2023\n",
      "•\n",
      "9\n",
      "•\n",
      "3\n",
      "huggingface/CodeBERTa-small-v1\n",
      "Fill-Mask\n",
      "•\n",
      "Updated\n",
      "Jun 27, 2022\n",
      "•\n",
      "39.9k\n",
      "•\n",
      "71\n",
      "huggingface/test-model-repo\n",
      "Updated\n",
      "Nov 19, 2021\n",
      "•\n",
      "1\n",
      "Expand 16\n",
      "\t\t\t\t\t\t\tmodels\n",
      "datasets\n",
      "31\n",
      "Sort: \n",
      "\t\tRecently updated\n",
      "huggingface/transformers-metadata\n",
      "Viewer\n",
      "•\n",
      "Updated\n",
      "about 1 hour ago\n",
      "•\n",
      "1.51k\n",
      "•\n",
      "674\n",
      "•\n",
      "13\n",
      "huggingface/policy-docs\n",
      "Updated\n",
      "about 14 hours ago\n",
      "•\n",
      "938\n",
      "•\n",
      "6\n",
      "huggingface/community-science-paper-v2\n",
      "Viewer\n",
      "•\n",
      "Updated\n",
      "about 14 hours ago\n",
      "•\n",
      "4.9k\n",
      "•\n",
      "337\n",
      "•\n",
      "6\n",
      "huggingface/documentation-images\n",
      "Viewer\n",
      "•\n",
      "Updated\n",
      "about 15 hours ago\n",
      "•\n",
      "44\n",
      "•\n",
      "2.61M\n",
      "•\n",
      "42\n",
      "huggingface/paper-central-data\n",
      "Viewer\n",
      "•\n",
      "Updated\n",
      "about 15 hours ago\n",
      "•\n",
      "112k\n",
      "•\n",
      "458\n",
      "•\n",
      "7\n",
      "huggingface/diffusers-metadata\n",
      "Viewer\n",
      "•\n",
      "Updated\n",
      "3 days ago\n",
      "•\n",
      "56\n",
      "•\n",
      "441\n",
      "•\n",
      "4\n",
      "huggingface/my-distiset-3f5a230e\n",
      "Updated\n",
      "21 days ago\n",
      "•\n",
      "15\n",
      "huggingface/cookbook-images\n",
      "Viewer\n",
      "•\n",
      "Updated\n",
      "29 days ago\n",
      "•\n",
      "1\n",
      "•\n",
      "47.1k\n",
      "•\n",
      "6\n",
      "huggingface/vllm-metadata\n",
      "Updated\n",
      "Oct 8\n",
      "•\n",
      "13\n",
      "huggingface/paper-central-data-2\n",
      "Viewer\n",
      "•\n",
      "Updated\n",
      "Oct 4\n",
      "•\n",
      "58.3k\n",
      "•\n",
      "69\n",
      "•\n",
      "2\n",
      "Expand 31\n",
      "\t\t\t\t\t\t\tdatasets\n",
      "Company\n",
      "© Hugging Face\n",
      "TOS\n",
      "Privacy\n",
      "About\n",
      "Jobs\n",
      "Website\n",
      "Models\n",
      "Datasets\n",
      "Spaces\n",
      "Pricing\n",
      "Docs\n",
      "\n",
      "\n",
      "\n",
      "blog page\n",
      "Webpage Title:\n",
      "Hugging Face – Blog\n",
      "Webpage Contents:\n",
      "Hugging Face\n",
      "Models\n",
      "Datasets\n",
      "Spaces\n",
      "Posts\n",
      "Docs\n",
      "Enterprise\n",
      "Pricing\n",
      "Log In\n",
      "Sign Up\n",
      "Blog, Articles, and discussions\n",
      "New Article\n",
      "Everything\n",
      "community\n",
      "guide\n",
      "open source collab\n",
      "partnerships\n",
      "research\n",
      "NLP\n",
      "Audio\n",
      "CV\n",
      "RL\n",
      "ethics\n",
      "Diffusion\n",
      "Game Development\n",
      "RLHF\n",
      "Leaderboard\n",
      "Case Studies\n",
      "LeMaterial: an open source initiative to accelerate materials discovery and research\n",
      "By\n",
      "AlexDuvalinho\n",
      "December 10, 2024\n",
      "guest\n",
      "•\n",
      "18\n",
      "Community Articles\n",
      "view all\n",
      "Introduction\n",
      "By\n",
      "hlky\n",
      "•\n",
      "about 13 hours ago\n",
      "🇪🇺✍️ EU AI Act: Systemic Risks in the First CoP Draft Comments ✍️🇪🇺\n",
      "By\n",
      "yjernite\n",
      "•\n",
      "about 15 hours ago\n",
      "•\n",
      "2\n",
      "The Intersection of CTMU and QCI: Implementing Emergent Intelligence\n",
      "By\n",
      "dimentox\n",
      "•\n",
      "about 24 hours ago\n",
      "Building an AI-powered search engine from scratch\n",
      "By\n",
      "as-cle-bert\n",
      "•\n",
      "1 day ago\n",
      "•\n",
      "4\n",
      "**Build Your Own AI Server at Home: A Cost-Effective Guide Using Pre-Owned Components**\n",
      "By\n",
      "theeseus-ai\n",
      "•\n",
      "1 day ago\n",
      "•\n",
      "1\n",
      "MotionLCM-V2: Improved Compression Rate for Multi-Latent-Token Diffusion\n",
      "By\n",
      "wxDai\n",
      "•\n",
      "2 days ago\n",
      "•\n",
      "9\n",
      "RLHF 101: A Technical Dive into RLHF\n",
      "By\n",
      "GitBag\n",
      "•\n",
      "2 days ago\n",
      "•\n",
      "1\n",
      "[Talk Arena](https://talkarena.org)\n",
      "By\n",
      "WillHeld\n",
      "•\n",
      "3 days ago\n",
      "Multimodal RAG with Colpali, Milvus and VLMs\n",
      "By\n",
      "saumitras\n",
      "•\n",
      "3 days ago\n",
      "In Honour of This Year's NeurIPs Test of Time Paper Awardees\n",
      "By\n",
      "Jaward\n",
      "•\n",
      "3 days ago\n",
      "•\n",
      "1\n",
      "Power steering: Squeeze massive power from small LLMs\n",
      "By\n",
      "ucheog\n",
      "•\n",
      "4 days ago\n",
      "•\n",
      "4\n",
      "Exploring the Power of KaibanJS v0.11.0 🚀\n",
      "By\n",
      "darielnoel\n",
      "•\n",
      "4 days ago\n",
      "•\n",
      "1\n",
      "**Building a Custom Retrieval System with Motoko and Node.js**\n",
      "By\n",
      "theeseus-ai\n",
      "•\n",
      "4 days ago\n",
      "Finding Moroccan Arabic (Darija) in Fineweb 2\n",
      "By\n",
      "omarkamali\n",
      "•\n",
      "5 days ago\n",
      "•\n",
      "17\n",
      "Running Your Custom LoRA Fine-Tuned MusicGen Large Locally\n",
      "By\n",
      "theeseus-ai\n",
      "•\n",
      "7 days ago\n",
      "•\n",
      "1\n",
      "Building a Local Vector Database Index with Annoy and Sentence Transformers\n",
      "By\n",
      "theeseus-ai\n",
      "•\n",
      "8 days ago\n",
      "•\n",
      "2\n",
      "Practical Consciousness Theory for AI System Design\n",
      "By\n",
      "KnutJaegersberg\n",
      "•\n",
      "8 days ago\n",
      "•\n",
      "3\n",
      "Releasing QwQ-LongCoT-130K\n",
      "By\n",
      "amphora\n",
      "•\n",
      "8 days ago\n",
      "•\n",
      "4\n",
      "They Said It Couldn’t Be Done\n",
      "By\n",
      "Pclanglais\n",
      "•\n",
      "8 days ago\n",
      "•\n",
      "68\n",
      "🐺🐦‍⬛ LLM Comparison/Test: 25 SOTA LLMs (including QwQ) through 59 MMLU-Pro CS benchmark runs\n",
      "By\n",
      "wolfram\n",
      "•\n",
      "8 days ago\n",
      "•\n",
      "68\n",
      "Hugging Face models in Amazon Bedrock\n",
      "By\n",
      "pagezyhf\n",
      "December 9, 2024\n",
      "•\n",
      "5\n",
      "Hugging Face Community Releases an Open Preference Dataset for Text-to-Image Generation\n",
      "By\n",
      "davidberenstein1957\n",
      "December 9, 2024\n",
      "•\n",
      "43\n",
      "Welcome PaliGemma 2 – New vision language models by Google\n",
      "By\n",
      "merve\n",
      "December 5, 2024\n",
      "•\n",
      "102\n",
      "“How good are LLMs at fixing their mistakes? A chatbot arena experiment with Keras and TPUs\n",
      "By\n",
      "martin-gorner\n",
      "December 5, 2024\n",
      "•\n",
      "11\n",
      "Rethinking LLM Evaluation with 3C3H: AraGen Benchmark and Leaderboard\n",
      "By\n",
      "alielfilali01\n",
      "December 4, 2024\n",
      "guest\n",
      "•\n",
      "24\n",
      "Investing in Performance: Fine-tune small models with LLM insights  - a CFM case study\n",
      "By\n",
      "oahouzi\n",
      "December 3, 2024\n",
      "•\n",
      "22\n",
      "Rearchitecting Hugging Face Uploads and Downloads\n",
      "By\n",
      "port8080\n",
      "November 26, 2024\n",
      "•\n",
      "37\n",
      "SmolVLM - small yet mighty Vision Language Model\n",
      "By\n",
      "andito\n",
      "November 26, 2024\n",
      "•\n",
      "132\n",
      "You could have designed state of the art positional encoding\n",
      "By\n",
      "FL33TW00D-HF\n",
      "November 25, 2024\n",
      "•\n",
      "72\n",
      "Letting Large Models Debate: The First Multilingual LLM Debate Competition\n",
      "By\n",
      "xuanricheng\n",
      "November 20, 2024\n",
      "guest\n",
      "•\n",
      "22\n",
      "From Files to Chunks: Improving Hugging Face Storage Efficiency\n",
      "By\n",
      "jsulz\n",
      "November 20, 2024\n",
      "•\n",
      "40\n",
      "Faster Text Generation with Self-Speculative Decoding\n",
      "By\n",
      "ariG23498\n",
      "November 20, 2024\n",
      "•\n",
      "41\n",
      "Introduction to the Open Leaderboard for Japanese LLMs\n",
      "By\n",
      "akimfromparis\n",
      "November 20, 2024\n",
      "guest\n",
      "•\n",
      "23\n",
      "Judge Arena: Benchmarking LLMs as Evaluators\n",
      "By\n",
      "kaikaidai\n",
      "November 19, 2024\n",
      "guest\n",
      "•\n",
      "45\n",
      "Previous\n",
      "1\n",
      "2\n",
      "3\n",
      "...\n",
      "36\n",
      "Next\n",
      "Community Articles\n",
      "view all\n",
      "Introduction\n",
      "By\n",
      "hlky\n",
      "•\n",
      "about 13 hours ago\n",
      "🇪🇺✍️ EU AI Act: Systemic Risks in the First CoP Draft Comments ✍️🇪🇺\n",
      "By\n",
      "yjernite\n",
      "•\n",
      "about 15 hours ago\n",
      "•\n",
      "2\n",
      "The Intersection of CTMU and QCI: Implementing Emergent Intelligence\n",
      "By\n",
      "dimentox\n",
      "•\n",
      "about 24 hours ago\n",
      "Building an AI-powered search engine from scratch\n",
      "By\n",
      "as-cle-bert\n",
      "•\n",
      "1 day ago\n",
      "•\n",
      "4\n",
      "**Build Your Own AI Server at Home: A Cost-Effective Guide Using Pre-Owned Components**\n",
      "By\n",
      "theeseus-ai\n",
      "•\n",
      "1 day ago\n",
      "•\n",
      "1\n",
      "MotionLCM-V2: Improved Compression Rate for Multi-Latent-Token Diffusion\n",
      "By\n",
      "wxDai\n",
      "•\n",
      "2 days ago\n",
      "•\n",
      "9\n",
      "RLHF 101: A Technical Dive into RLHF\n",
      "By\n",
      "GitBag\n",
      "•\n",
      "2 days ago\n",
      "•\n",
      "1\n",
      "[Talk Arena](https://talkarena.org)\n",
      "By\n",
      "WillHeld\n",
      "•\n",
      "3 days ago\n",
      "Multimodal RAG with Colpali, Milvus and VLMs\n",
      "By\n",
      "saumitras\n",
      "•\n",
      "3 days ago\n",
      "In Honour of This Year's NeurIPs Test of Time Paper Awardees\n",
      "By\n",
      "Jaward\n",
      "•\n",
      "3 days ago\n",
      "•\n",
      "1\n",
      "Power steering: Squeeze massive power from small LLMs\n",
      "By\n",
      "ucheog\n",
      "•\n",
      "4 days ago\n",
      "•\n",
      "4\n",
      "Exploring the Power of KaibanJS v0.11.0 🚀\n",
      "By\n",
      "darielnoel\n",
      "•\n",
      "4 days ago\n",
      "•\n",
      "1\n",
      "**Building a Custom Retrieval System with Motoko and Node.js**\n",
      "By\n",
      "theeseus-ai\n",
      "•\n",
      "4 days ago\n",
      "Finding Moroccan Arabic (Darija) in Fineweb 2\n",
      "By\n",
      "omarkamali\n",
      "•\n",
      "5 days ago\n",
      "•\n",
      "17\n",
      "Running Your Custom LoRA Fine-Tuned MusicGen Large Locally\n",
      "By\n",
      "theeseus-ai\n",
      "•\n",
      "7 days ago\n",
      "•\n",
      "1\n",
      "Building a Local Vector Database Index with Annoy and Sentence Transformers\n",
      "By\n",
      "theeseus-ai\n",
      "•\n",
      "8 days ago\n",
      "•\n",
      "2\n",
      "Practical Consciousness Theory for AI System Design\n",
      "By\n",
      "KnutJaegersberg\n",
      "•\n",
      "8 days ago\n",
      "•\n",
      "3\n",
      "Releasing QwQ-LongCoT-130K\n",
      "By\n",
      "amphora\n",
      "•\n",
      "8 days ago\n",
      "•\n",
      "4\n",
      "They Said It Couldn’t Be Done\n",
      "By\n",
      "Pclanglais\n",
      "•\n",
      "8 days ago\n",
      "•\n",
      "68\n",
      "🐺🐦‍⬛ LLM Comparison/Test: 25 SOTA LLMs (including QwQ) through 59 MMLU-Pro CS benchmark runs\n",
      "By\n",
      "wolfram\n",
      "•\n",
      "8 days ago\n",
      "•\n",
      "68\n",
      "Company\n",
      "© Hugging Face\n",
      "TOS\n",
      "Privacy\n",
      "About\n",
      "Jobs\n",
      "Website\n",
      "Models\n",
      "Datasets\n",
      "Spaces\n",
      "Pricing\n",
      "Docs\n",
      "\n",
      "\n",
      "\n",
      "enterprise page\n",
      "Webpage Title:\n",
      "Enterprise Hub - Hugging Face\n",
      "Webpage Contents:\n",
      "Hugging Face\n",
      "Models\n",
      "Datasets\n",
      "Spaces\n",
      "Posts\n",
      "Docs\n",
      "Enterprise\n",
      "Pricing\n",
      "Log In\n",
      "Sign Up\n",
      "Enterprise Hub\n",
      "Enterprise-ready version of the world’s leading AI platform\n",
      "Subscribe to\n",
      "Enterprise Hub\n",
      "for $20/user/month with your Hub organization\n",
      "Give your organization the most advanced platform to build AI with enterprise-grade security, access controls,\n",
      "\t\t\tdedicated support and more.\n",
      "Single Sign-On\n",
      "Connect securely to your identity provider with SSO integration.\n",
      "Regions\n",
      "Select, manage, and audit the location of your repository data.\n",
      "Audit Logs\n",
      "Stay in control with comprehensive logs that report on actions taken.\n",
      "Resource Groups\n",
      "Accurately manage access to repositories with granular access control.\n",
      "Token Management\n",
      "Centralized token control and custom approval policies for organization access.\n",
      "Analytics\n",
      "Track and analyze repository usage data in a single dashboard.\n",
      "Advanced Compute Options\n",
      "Increase scalability and performance with more compute options like ZeroGPU for Spaces.\n",
      "Private Datasets Viewer\n",
      "Enable the Dataset Viewer on your private datasets for easier collaboration.\n",
      "Advanced security\n",
      "Configure organization-wide security policies and default repository visibility.\n",
      "Billing\n",
      "Control your budget effectively with managed billing and yearly commit options.\n",
      "Priority Support\n",
      "Maximize your platform usage with priority support from the Hugging Face team.\n",
      "Join the most forward-thinking AI organizations\n",
      "Everything you already know and love about Hugging Face in Enterprise mode.\n",
      "Subscribe to\n",
      "Enterprise Hub\n",
      "or\n",
      "Talk to sales\n",
      "AI at Meta\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "2.05k models\n",
      "•\n",
      "3.74k followers\n",
      "Nerdy Face\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "1 model\n",
      "•\n",
      "234 followers\n",
      "ServiceNow-AI\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "108 followers\n",
      "Deutsche Telekom AG\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "7 models\n",
      "•\n",
      "112 followers\n",
      "Chegg Inc\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "77 followers\n",
      "Lightricks\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "3 models\n",
      "•\n",
      "357 followers\n",
      "Aledade Inc\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "53 followers\n",
      "Liberty Mutual\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "41 followers\n",
      "Arcee AI\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "130 models\n",
      "•\n",
      "259 followers\n",
      "Ekimetrics\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "47 followers\n",
      "Johnson & Johnson\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "35 followers\n",
      "Vectara\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "1 model\n",
      "•\n",
      "54 followers\n",
      "HOVER External\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "26 followers\n",
      "Qualcomm\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "153 models\n",
      "•\n",
      "350 followers\n",
      "Meta Llama\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "57 models\n",
      "•\n",
      "13k followers\n",
      "Orange\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "4 models\n",
      "•\n",
      "147 followers\n",
      "Writer\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "15 models\n",
      "•\n",
      "178 followers\n",
      "Toyota Research Institute\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "8 models\n",
      "•\n",
      "91 followers\n",
      "H2O.ai\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "71 models\n",
      "•\n",
      "359 followers\n",
      "Mistral AI_\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "21 models\n",
      "•\n",
      "3.36k followers\n",
      "IBM Granite\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "56 models\n",
      "•\n",
      "600 followers\n",
      "Nutanix\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "245 models\n",
      "•\n",
      "38 followers\n",
      "Virtusa Corporation\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "46 followers\n",
      "creditkarma\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "32 followers\n",
      "Gsk-tech\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "33 followers\n",
      "BCG X\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "29 followers\n",
      "StepStone Online Recruiting\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "32 followers\n",
      "Prezi\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "30 followers\n",
      "Shopify\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "370 followers\n",
      "Together\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "27 models\n",
      "•\n",
      "460 followers\n",
      "Bloomberg\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "2 models\n",
      "•\n",
      "132 followers\n",
      "Fidelity Investments\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "114 followers\n",
      "Jusbrasil\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "77 followers\n",
      "Technology Innovation Institute\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "25 models\n",
      "•\n",
      "977 followers\n",
      "Stability AI\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "95 models\n",
      "•\n",
      "8.45k followers\n",
      "HiddenLayer\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "49 followers\n",
      "Kakao Corp.\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "41 followers\n",
      "Gretel.ai\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "8 models\n",
      "•\n",
      "69 followers\n",
      "Mercedes-Benz AG\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "80 followers\n",
      "Widn AI\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "27 followers\n",
      "Liquid AI\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "85 followers\n",
      "BRIA AI\n",
      "Enterprise\n",
      "company\n",
      "•\n",
      "28 models\n",
      "•\n",
      "931 followers\n",
      "Compliance & Certifications\n",
      "GDPR Compliant\n",
      "SOC 2 Type 2\n",
      "Website\n",
      "Models\n",
      "Datasets\n",
      "Spaces\n",
      "Tasks\n",
      "Inference Endpoints\n",
      "HuggingChat\n",
      "Company\n",
      "About\n",
      "Brand assets\n",
      "Terms of service\n",
      "Privacy\n",
      "Jobs\n",
      "Press\n",
      "Resources\n",
      "Learn\n",
      "Documentation\n",
      "Blog\n",
      "Forum\n",
      "Service Status\n",
      "Social\n",
      "GitHub\n",
      "Twitter\n",
      "LinkedIn\n",
      "Discord\n",
      "\n",
      "\n",
      "\n",
      "pricing page\n",
      "Webpage Title:\n",
      "Hugging Face – Pricing\n",
      "Webpage Contents:\n",
      "Hugging Face\n",
      "Models\n",
      "Datasets\n",
      "Spaces\n",
      "Posts\n",
      "Docs\n",
      "Enterprise\n",
      "Pricing\n",
      "Log In\n",
      "Sign Up\n",
      "Pricing\n",
      "Leveling up AI collaboration and compute.\n",
      "Users and organizations already use the Hub as a collaboration platform,\n",
      "we’re making it easy to seamlessly and scalably launch ML compute directly from the Hub.\n",
      "HF Hub\n",
      "Collaborate on Machine Learning\n",
      "Host unlimited public models, datasets\n",
      "Create unlimited orgs with no member limits\n",
      "Access the latest ML tools and open source\n",
      "Community support\n",
      "Forever\n",
      "Free\n",
      "PRO\n",
      "Pro Account\n",
      "Unlock advanced HF features\n",
      "ZeroGPU and Dev Mode for Spaces\n",
      "Higher rate limits for serverless inference\n",
      "Get early access to upcoming features\n",
      "Show your support with a Pro badge\n",
      "Subscribe for\n",
      "$9\n",
      "/month\n",
      "Enterprise Hub\n",
      "Accelerate your AI roadmap\n",
      "SSO and SAML support\n",
      "Select data location with Storage Regions\n",
      "Precise actions reviews with Audit logs\n",
      "Granular access control with Resource groups\n",
      "Centralized token control and approval\n",
      "Dataset Viewer for private datasets\n",
      "Advanced compute options for Spaces\n",
      "Deploy Inference on your own Infra\n",
      "Managed billing with yearly commits\n",
      "Priority support\n",
      "Starting at\n",
      "$20\n",
      "per user per month\n",
      "Spaces Hardware\n",
      "Upgrade your Space compute\n",
      "Free CPUs\n",
      "Build more advanced Spaces\n",
      "7 optimized hardware available\n",
      "From CPU to GPU to Accelerators\n",
      "Starting at\n",
      "$0\n",
      "/hour\n",
      "Inference Endpoints\n",
      "Deploy models on fully managed infrastructure\n",
      "Deploy dedicated Endpoints in seconds\n",
      "Keep your costs low\n",
      "Fully-managed autoscaling\n",
      "Enterprise security\n",
      "Starting at\n",
      "$0.032\n",
      "/hour\n",
      "Need support to accelerate AI in your organization? View our\n",
      "Expert Support\n",
      ".\n",
      "Hugging Face Hub\n",
      "free\n",
      "The HF Hub is the central place to explore, experiment, collaborate and build technology with Machine\n",
      "\t\t\t\t\tLearning.\n",
      "Join the open source Machine Learning movement!\n",
      "→\n",
      "Sign Up\n",
      "Create with ML\n",
      "Packed with ML features, like model eval, dataset viewer and much more.\n",
      "Collaborate\n",
      "Git based and designed for collaboration at its core.\n",
      "Play and learn\n",
      "Learn by experimenting and sharing with our awesome community.\n",
      "Build your ML portfolio\n",
      "Share your work with the world and build your own ML profile.\n",
      "Spaces Hardware\n",
      "Starting at $0\n",
      "Spaces are one of the most popular ways to share ML applications and demos with the world.\n",
      "Upgrade your Spaces with our selection of custom on-demand hardware:\n",
      "→\n",
      "Get started with Spaces\n",
      "Name\n",
      "CPU\n",
      "Memory\n",
      "Accelerator\n",
      "VRAM\n",
      "Hourly price\n",
      "CPU Basic\n",
      "2 vCPU\n",
      "16 GB\n",
      "-\n",
      "-\n",
      "FREE\n",
      "CPU Upgrade\n",
      "8 vCPU\n",
      "32 GB\n",
      "-\n",
      "-\n",
      "$0.03\n",
      "Nvidia T4 - small\n",
      "4 vCPU\n",
      "15 GB\n",
      "Nvidia T4\n",
      "16 GB\n",
      "$0.40\n",
      "Nvidia T4 - medium\n",
      "8 vCPU\n",
      "30 GB\n",
      "Nvidia T4\n",
      "16 GB\n",
      "$0.60\n",
      "1x Nvidia L4\n",
      "8 vCPU\n",
      "30 GB\n",
      "Nvidia L4\n",
      "24 GB\n",
      "$0.80\n",
      "4x Nvidia L4\n",
      "48 vCPU\n",
      "186 GB\n",
      "Nvidia L4\n",
      "96 GB\n",
      "$3.80\n",
      "1x Nvidia L40S\n",
      "8 vCPU\n",
      "62 GB\n",
      "Nvidia L4\n",
      "48 GB\n",
      "$1.80\n",
      "4x Nvidia L40S\n",
      "48 vCPU\n",
      "382 GB\n",
      "Nvidia L4\n",
      "192 GB\n",
      "$8.30\n",
      "8x Nvidia L40S\n",
      "192 vCPU\n",
      "1534 GB\n",
      "Nvidia L4\n",
      "384 GB\n",
      "$23.50\n",
      "Nvidia A10G - small\n",
      "4 vCPU\n",
      "15 GB\n",
      "Nvidia A10G\n",
      "24 GB\n",
      "$1.00\n",
      "Nvidia A10G - large\n",
      "12 vCPU\n",
      "46 GB\n",
      "Nvidia A10G\n",
      "24 GB\n",
      "$1.50\n",
      "2x Nvidia A10G - large\n",
      "24 vCPU\n",
      "92 GB\n",
      "Nvidia A10G\n",
      "48 GB\n",
      "$3.00\n",
      "4x Nvidia A10G - large\n",
      "48 vCPU\n",
      "184 GB\n",
      "Nvidia A10G\n",
      "96 GB\n",
      "$5.00\n",
      "Nvidia A100 - large\n",
      "12 vCPU\n",
      "142 GB\n",
      "Nvidia A100\n",
      "80 GB\n",
      "$4.00\n",
      "TPU v5e 1x1\n",
      "22 vCPU\n",
      "44 GB\n",
      "Google TPU v5e\n",
      "16 GB\n",
      "$1.20\n",
      "TPU v5e 2x2\n",
      "110 vCPU\n",
      "186 GB\n",
      "Google TPU v5e\n",
      "64 GB\n",
      "$4.75\n",
      "TPU v5e 2x4\n",
      "220 vCPU\n",
      "380 GB\n",
      "Google TPU v5e\n",
      "128 GB\n",
      "$9.50\n",
      "Custom\n",
      "on demand\n",
      "on demand\n",
      "on demand\n",
      "on demand\n",
      "on demand\n",
      "Spaces Persistent Storage\n",
      "All Spaces get ephemeral storage for free but you can upgrade and add persistent storage at any time.\n",
      "Name\n",
      "Storage\n",
      "Monthly price\n",
      "Small\n",
      "20 GB\n",
      "$5\n",
      "Medium\n",
      "150 GB\n",
      "$25\n",
      "Large\n",
      "1 TB\n",
      "$100\n",
      "Building something cool as a side project? We also offer community GPU grants.\n",
      "Inference Endpoints\n",
      "Starting at $0.033/hour\n",
      "Inference Endpoints (dedicated) offers a secure production solution to easily deploy any ML model on dedicated\n",
      "\t\t\t\t\tand autoscaling infrastructure, right from the HF Hub.\n",
      "→\n",
      "Learn more\n",
      "CPU\n",
      "instances\n",
      "Provider\n",
      "Architecture\n",
      "vCPUs\n",
      "Memory\n",
      "Hourly rate\n",
      "aws\n",
      "Intel Sapphire Rapids\n",
      "1\n",
      "2GB\n",
      "$0.03\n",
      "2\n",
      "4GB\n",
      "$0.07\n",
      "4\n",
      "8GB\n",
      "$0.13\n",
      "8\n",
      "16GB\n",
      "$0.27\n",
      "azure\n",
      "Intel Xeon\n",
      "1\n",
      "2GB\n",
      "$0.06\n",
      "2\n",
      "4GB\n",
      "$0.12\n",
      "4\n",
      "8GB\n",
      "$0.24\n",
      "8\n",
      "16GB\n",
      "$0.48\n",
      "gcp\n",
      "Intel Sapphire Rapids\n",
      "1\n",
      "2GB\n",
      "$0.05\n",
      "2\n",
      "4GB\n",
      "$0.10\n",
      "4\n",
      "8GB\n",
      "$0.20\n",
      "8\n",
      "16GB\n",
      "$0.40\n",
      "Accelerator\n",
      "instances\n",
      "Provider\n",
      "Architecture\n",
      "Topology\n",
      "Accelerator Memory\n",
      "Hourly rate\n",
      "aws\n",
      "Inf2\n",
      "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tNeuron\n",
      "x1\n",
      "14.5GB\n",
      "$0.75\n",
      "x12\n",
      "760GB\n",
      "$12.00\n",
      "gcp\n",
      "TPU\n",
      "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tv5e\n",
      "1x1\n",
      "16GB\n",
      "$1.20\n",
      "2x2\n",
      "64GB\n",
      "$4.75\n",
      "2x4\n",
      "128GB\n",
      "$9.50\n",
      "GPU\n",
      "instances\n",
      "Provider\n",
      "Architecture\n",
      "GPUs\n",
      "GPU Memory\n",
      "Hourly rate\n",
      "aws\n",
      "NVIDIA T4\n",
      "1\n",
      "14GB\n",
      "$0.50\n",
      "4\n",
      "56GB\n",
      "$3.00\n",
      "aws\n",
      "NVIDIA L4\n",
      "1\n",
      "24GB\n",
      "$0.80\n",
      "4\n",
      "96GB\n",
      "$3.80\n",
      "aws\n",
      "NVIDIA L40S\n",
      "1\n",
      "48GB\n",
      "$1.80\n",
      "4\n",
      "192GB\n",
      "$8.30\n",
      "8\n",
      "384GB\n",
      "$23.50\n",
      "aws\n",
      "NVIDIA A10G\n",
      "1\n",
      "24GB\n",
      "$1.00\n",
      "4\n",
      "96GB\n",
      "$5.00\n",
      "aws\n",
      "NVIDIA A100\n",
      "1\n",
      "80GB\n",
      "$4.00\n",
      "2\n",
      "160GB\n",
      "$8.00\n",
      "4\n",
      "320GB\n",
      "$16.00\n",
      "8\n",
      "640GB\n",
      "$32.00\n",
      "gcp\n",
      "NVIDIA T4\n",
      "1\n",
      "16GB\n",
      "$0.50\n",
      "gcp\n",
      "NVIDIA L4\n",
      "1\n",
      "24GB\n",
      "$0.70\n",
      "4\n",
      "96GB\n",
      "$3.80\n",
      "gcp\n",
      "NVIDIA A100\n",
      "1\n",
      "80GB\n",
      "$3.60\n",
      "2\n",
      "160GB\n",
      "$7.20\n",
      "4\n",
      "320GB\n",
      "$14.40\n",
      "8\n",
      "640GB\n",
      "$28.80\n",
      "gcp\n",
      "NVIDIA H100\n",
      "1\n",
      "80GB\n",
      "$10.00\n",
      "2\n",
      "160GB\n",
      "$20.00\n",
      "4\n",
      "320GB\n",
      "$40.00\n",
      "8\n",
      "640GB\n",
      "$80.00\n",
      "Pro Account\n",
      "PRO\n",
      "A monthly subscription to access powerful features.\n",
      "→\n",
      "Get Pro\n",
      "($9/month)\n",
      "ZeroGPU\n",
      ": Get 5x usage quota and highest GPU queue priority\n",
      "Spaces Hosting\n",
      ": Create ZeroGPU Spaces with A100 hardware\n",
      "Spaces Dev Mode\n",
      ": Fast iterations via SSH/VS Code for Spaces\n",
      "Dataset Viewer\n",
      ": Activate it on private datasets\n",
      "Inference API\n",
      ": Get x20 higher rate limits on Serverless API\n",
      "Blog Articles\n",
      ": Publish articles to the Hugging Face blog\n",
      "Social Posts\n",
      ": Share short updates with the community\n",
      "Features Preview\n",
      ": Get early access to upcoming\n",
      "\t\t\t\t\t\t\t\t\t\tfeatures\n",
      "PRO\n",
      "Badge\n",
      ":\n",
      "\t\t\t\t\t\t\t\t\t\tShow your support on your profile\n",
      "Website\n",
      "Models\n",
      "Datasets\n",
      "Spaces\n",
      "Tasks\n",
      "Inference Endpoints\n",
      "HuggingChat\n",
      "Company\n",
      "About\n",
      "Brand assets\n",
      "Terms of service\n",
      "Privacy\n",
      "Jobs\n",
      "Press\n",
      "Resources\n",
      "Learn\n",
      "Documentation\n",
      "Blog\n",
      "Forum\n",
      "Service Status\n",
      "Social\n",
      "GitHub\n",
      "Twitter\n",
      "LinkedIn\n",
      "Discord\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print(get_all_details(\"https://huggingface.co\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "9b863a55-f86c-4e3f-8a79-94e24c1a8cf2",
   "metadata": {},
   "outputs": [],
   "source": [
    "system_prompt = \"You are an assistant that analyzes the contents of several relevant pages from a company website \\\n",
    "and creates a short brochure about the company for prospective customers, investors and recruits. Respond in markdown.\\\n",
    "Include details of company culture, customers and careers/jobs if you have the information.\"\n",
    "\n",
    "# Or uncomment the lines below for a more humorous brochure - this demonstrates how easy it is to incorporate 'tone':\n",
    "\n",
    "# system_prompt = \"You are an assistant that analyzes the contents of several relevant pages from a company website \\\n",
    "# and creates a short humorous, entertaining, jokey brochure about the company for prospective customers, investors and recruits. Respond in markdown.\\\n",
    "# Include details of company culture, customers and careers/jobs if you have the information.\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "6ab83d92-d36b-4ce0-8bcc-5bb4c2f8ff23",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_brochure_user_prompt(company_name, url):\n",
    "    user_prompt = f\"You are looking at a company called: {company_name}\\n\"\n",
    "    user_prompt += f\"Here are the contents of its landing page and other relevant pages; use this information to build a short brochure of the company in markdown.\\n\"\n",
    "    user_prompt += get_all_details(url)\n",
    "    user_prompt = user_prompt[:5_000] # Truncate if more than 5,000 characters\n",
    "    return user_prompt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "cd909e0b-1312-4ce2-a553-821e795d7572",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found links: {'links': [{'type': 'about page', 'url': 'https://huggingface.co/huggingface'}, {'type': 'careers page', 'url': 'https://apply.workable.com/huggingface/'}, {'type': 'enterprise page', 'url': 'https://huggingface.co/enterprise'}, {'type': 'pricing page', 'url': 'https://huggingface.co/pricing'}, {'type': 'blog page', 'url': 'https://huggingface.co/blog'}, {'type': 'contact/discussion page', 'url': 'https://discuss.huggingface.co'}, {'type': 'GitHub page', 'url': 'https://github.com/huggingface'}, {'type': 'LinkedIn page', 'url': 'https://www.linkedin.com/company/huggingface/'}, {'type': 'Twitter page', 'url': 'https://twitter.com/huggingface'}]}\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "\"You are looking at a company called: HuggingFace\\nHere are the contents of its landing page and other relevant pages; use this information to build a short brochure of the company in markdown.\\nLanding page:\\nWebpage Title:\\nHugging Face – The AI community building the future.\\nWebpage Contents:\\nHugging Face\\nModels\\nDatasets\\nSpaces\\nPosts\\nDocs\\nEnterprise\\nPricing\\nLog In\\nSign Up\\nThe AI community building the future.\\nThe platform where the machine learning community collaborates on models, datasets, and applications.\\nTrending on\\nthis week\\nModels\\nmeta-llama/Llama-3.3-70B-Instruct\\nUpdated\\n3 days ago\\n•\\n102k\\n•\\n937\\ntencent/HunyuanVideo\\nUpdated\\n6 days ago\\n•\\n3.73k\\n•\\n978\\nDatou1111/shou_xin\\nUpdated\\n4 days ago\\n•\\n7.84k\\n•\\n273\\nblack-forest-labs/FLUX.1-dev\\nUpdated\\nAug 16\\n•\\n1.38M\\n•\\n7.22k\\nQwen/QwQ-32B-Preview\\nUpdated\\n14 days ago\\n•\\n92.8k\\n•\\n1.26k\\nBrowse 400k+ models\\nSpaces\\nRunning\\non\\nZero\\n1.08k\\n🏢\\nTRELLIS\\nScalable and Versatile 3D Generation from images\\nRunning\\non\\nZero\\n281\\n🦀🏆\\nFLUXllama\\nFLUX 4-bit Quantization(just 8GB VRAM)\\nRunning\\non\\nL40S\\n225\\n🚀\\nFlux Style Shaping\\nOptical illusions and style transfer with FLUX\\nRunning\\non\\nCPU Upgrade\\n5.91k\\n👕\\nKolors Virtual Try-On\\nRunning\\non\\nZero\\n478\\n🌍\\nOminiControl\\nBrowse 150k+ applications\\nDatasets\\nHuggingFaceFW/fineweb-2\\nUpdated\\n5 days ago\\n•\\n21.1k\\n•\\n275\\nfka/awesome-chatgpt-prompts\\nUpdated\\nSep 3\\n•\\n7.94k\\n•\\n6.51k\\nCohereForAI/Global-MMLU\\nUpdated\\nabout 20 hours ago\\n•\\n3.67k\\n•\\n75\\nO1-OPEN/OpenO1-SFT\\nUpdated\\n21 days ago\\n•\\n1.27k\\n•\\n171\\namphora/QwQ-LongCoT-130K\\nUpdated\\n8 days ago\\n•\\n433\\n•\\n44\\nBrowse 100k+ datasets\\nThe Home of Machine Learning\\nCreate, discover and collaborate on ML better.\\nThe collaboration platform\\nHost and collaborate on unlimited public models, datasets and applications.\\nMove faster\\nWith the HF Open source stack.\\nExplore all modalities\\nText, image, video, audio or even 3D.\\nBuild your portfolio\\nShare your work with the world and build your ML profile.\\nSign Up\\nAccelerate your ML\\nWe provide paid Compute and Enterprise solutions.\\nCompute\\nDeploy on optimized\\nInference Endpoints\\nor update your\\nSpaces applications\\nto a GPU in a few clicks.\\nView pricing\\nStarting at $0.60/hour for GPU\\nEnterprise\\nGive your team the most advanced platform to build AI with enterprise-grade security, access controls and\\n\\t\\t\\tdedicated support.\\nGetting started\\nStarting at $20/user/month\\nSingle Sign-On\\nRegions\\nPriority Support\\nAudit Logs\\nResource Groups\\nPrivate Datasets Viewer\\nMore than 50,000 organizations are using Hugging Face\\nAi2\\nEnterprise\\nnon-profit\\n•\\n361 models\\n•\\n1.71k followers\\nAI at Meta\\nEnterprise\\ncompany\\n•\\n2.05k models\\n•\\n3.74k followers\\nAmazon Web Services\\ncompany\\n•\\n21 models\\n•\\n2.41k followers\\nGoogle\\ncompany\\n•\\n910 models\\n•\\n5.44k followers\\nIntel\\ncompany\\n•\\n217 models\\n•\\n2.05k followers\\nMicrosoft\\ncompany\\n•\\n351 models\\n•\\n6.03k followers\\nGrammarly\\ncompany\\n•\\n10 models\\n•\\n98 followers\\nWriter\\nEnterprise\\ncompany\\n•\\n15 models\\n•\\n178 followers\\nOur Open Source\\nWe are building the foundation of ML tooling with the community.\\nTransformers\\n136,226\\nState-of-the-art ML for Pytorch, TensorFlow, and JAX.\\nDiffusers\\n26,619\\nState-of-the-art diffusion models for image and audio generation in PyTorch.\\nSafetensors\\n2,950\\nSimple, safe way to store and distribute neural networks weights safely and quickly.\\nHub Python Library\\n2,165\\nClient library for the HF Hub: manage repositories from your Python runtime.\\nTokenizers\\n9,149\\nFast tokenizers, optimized for both research and production.\\nPEFT\\n16,695\\nParameter efficient finetuning methods for large models.\\nTransformers.js\\n12,336\\nState-of-the-art Machine Learning for the web. Run Transformers directly in your browser, with no need for a server.\\ntimm\\n32,588\\nState-of-the-art computer vision models, layers, optimizers, training/evaluation, and utilities.\\nTRL\\n10,305\\nTrain transformer language models with reinforcement learning.\\nDatasets\\n19,348\\nAccess and share datasets for computer vision, audio, and NLP tasks.\\nText Generation Inference\\n9,407\\nToolkit to serve Large Language Models.\\nAccelerate\\n8,049\\nEasily train and use PyTorch models with multi-GPU, TPU, mixed-precision.\\nWebsite\\nModels\\nDatasets\\nSpaces\\nTasks\\nInference Endpoints\\nHuggingChat\\nCompany\\nAbout\\nBrand assets\\nTerms of service\\nPrivacy\\nJobs\\nPress\\nResources\\nLearn\\nDocumentation\\nBlog\\nForum\\nService Status\\nSocial\\nGitHub\\nTwitter\\nLinkedIn\\nDiscord\\nZhihu\\nWeChat\\n\\n\\n\\nabout page\\nWebpage Title:\\nhuggingface (Hugging Face)\\nWebpage Contents:\\nHugging Face\\nModels\\nDatasets\\nSpaces\\nPosts\\nDocs\\nEnterprise\\nPricing\\nLog In\\nSign Up\\nHugging Face\\nEnterprise\\ncompany\\nVerified\\nhttps://huggingface.co\\nhuggingface\\nhuggingface\\nFollow\\n7,398\\nAI & ML interests\\nThe AI community building the future.\\nTeam members\\n224\\n+190\\n+177\\n+156\\n+146\\n+126\\nOrganization Card\\nCommunity\\nAbout org cards\\n👋 Hi!\\nWe are on a mission to democratize\\ngood\\nmachine learning, one commit at a time.\\nIf that sounds like something you should be doing, why don't you\\njoin us\\n!\\nFor press enquiries, you can\\n✉️ contact our team here\\n.\\nCollections\\n1\\nDistilBERT release\\nOriginal DistilBERT model, checkpoints obtained from using teacher-stude\""
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "get_brochure_user_prompt(\"HuggingFace\", \"https://huggingface.co\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "e44de579-4a1a-4e6a-a510-20ea3e4b8d46",
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_brochure(company_name, url):\n",
    "    response = openai.chat.completions.create(\n",
    "        model=MODEL,\n",
    "        messages=[\n",
    "            {\"role\": \"system\", \"content\": system_prompt},\n",
    "            {\"role\": \"user\", \"content\": get_brochure_user_prompt(company_name, url)}\n",
    "          ],\n",
    "    )\n",
    "    result = response.choices[0].message.content\n",
    "    display(Markdown(result))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "e093444a-9407-42ae-924a-145730591a39",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found links: {'links': [{'type': 'about page', 'url': 'https://huggingface.com/huggingface'}, {'type': 'careers page', 'url': 'https://apply.workable.com/huggingface/'}, {'type': 'company page', 'url': 'https://hugginface.com/enterprise'}]}\n"
     ]
    },
    {
     "data": {
      "text/markdown": [
       "# Hugging Face Brochure\n",
       "\n",
       "## Overview\n",
       "### Hugging Face – The AI community building the future\n",
       "Hugging Face is a leading platform in the field of artificial intelligence and machine learning, dedicated to creating a collaborative environment where the community can discover, share, and build upon state-of-the-art models and datasets. With over **400,000 models** and **100,000 datasets**, Hugging Face empowers users to harness the power of machine learning across various modalities including text, images, video, audio, and even 3D creations.\n",
       "\n",
       "## Our Mission\n",
       "We are on a mission to **democratize good machine learning**, believing that machine learning tools should be accessible for everyone, enabling innovation and collaboration across various sectors. \n",
       "\n",
       "## Our Offerings\n",
       "Hugging Face provides a robust suite of resources:\n",
       "- **Models**: Access a diverse range of pre-trained models such as the **Llama-3.3-70B-Instruct** and **HunyuanVideo**, and contribute to the evolution of machine learning.\n",
       "- **Datasets**: Explore and share extensive datasets tailored for multiple applications including computer vision and natural language processing.\n",
       "- **Spaces**: Deploy and collaborate on applications in a scalable manner.\n",
       "- **Enterprise Solutions**: Tailored offerings for organizations seeking advanced tools with added security, user access controls, and dedicated support.\n",
       "\n",
       "### Trending Resources\n",
       "- **Models**: Stay updated with trending models being actively developed by our community.\n",
       "- **Spaces**: Discover innovative applications powered by machine learning.\n",
       "\n",
       "## Company Culture\n",
       "Hugging Face fosters a vibrant and inclusive company culture that emphasizes collaboration, open-source ethos, and community involvement. With over **224 team members**, our workforce is composed of diverse talents united by a shared purpose and commitment to advancing AI technology. \n",
       "\n",
       "We actively encourage our team to contribute to the open-source community, aligning with our mission to create a **community-driven ecosystem of machine learning tools**. \n",
       "\n",
       "### Join Us\n",
       "Interested in being part of our mission? We’re continuously looking for passionate individuals to join our team. Positions vary across technical, operational, and creative roles, offering the opportunity to shape the future of AI.\n",
       "\n",
       "## Our Customers\n",
       "Hugging Face serves **over 50,000 organizations**, including industry giants like **Amazon Web Services, Google, Microsoft**, and several startups striving to leverage AI for transformative purposes. \n",
       "\n",
       "## Careers at Hugging Face\n",
       "Explore job openings across various domains:\n",
       "- Software Engineering\n",
       "- Data Science\n",
       "- Community Management\n",
       "- Operations and Marketing\n",
       "\n",
       "Be a part of a dynamic team working on groundbreaking AI technology. \n",
       "\n",
       "## Get Started\n",
       "Join our community today by signing up on our platform or explore our offerings to see how you can leverage machine learning for your own projects.\n",
       "\n",
       "[**Visit Hugging Face**](https://huggingface.co/)\n",
       "\n",
       "---\n",
       "\n",
       "**Connect with Us:**\n",
       "- GitHub\n",
       "- Twitter\n",
       "- LinkedIn\n",
       "- Discord\n",
       "\n",
       "Follow us to stay updated on the latest in AI and machine learning!"
      ],
      "text/plain": [
       "<IPython.core.display.Markdown object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "create_brochure(\"HuggingFace\", \"https://huggingface.com\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "61eaaab7-0b47-4b29-82d4-75d474ad8d18",
   "metadata": {},
   "source": [
    "## Finally - a minor improvement\n",
    "\n",
    "With a small adjustment, we can change this so that the results stream back from OpenAI,\n",
    "with the familiar typewriter animation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "51db0e49-f261-4137-aabe-92dd601f7725",
   "metadata": {},
   "outputs": [],
   "source": [
    "def stream_brochure(company_name, url):\n",
    "    stream = openai.chat.completions.create(\n",
    "        model=MODEL,\n",
    "        messages=[\n",
    "            {\"role\": \"system\", \"content\": system_prompt},\n",
    "            {\"role\": \"user\", \"content\": get_brochure_user_prompt(company_name, url)}\n",
    "          ],\n",
    "        stream=True\n",
    "    )\n",
    "    \n",
    "    response = \"\"\n",
    "    display_handle = display(Markdown(\"\"), display_id=True)\n",
    "    for chunk in stream:\n",
    "        response += chunk.choices[0].delta.content or ''\n",
    "        response = response.replace(\"```\",\"\").replace(\"markdown\", \"\")\n",
    "        update_display(Markdown(response), display_id=display_handle.display_id)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "56bf0ae3-ee9d-4a72-9cd6-edcac67ceb6d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found links: {'links': [{'type': 'about page', 'url': 'https://huggingface.co'}, {'type': 'careers page', 'url': 'https://apply.workable.com/huggingface/'}, {'type': 'company page', 'url': 'https://www.linkedin.com/company/huggingface/'}]}\n"
     ]
    },
    {
     "data": {
      "text/markdown": [
       "# Hugging Face Brochure\n",
       "\n",
       "## About Us\n",
       "**Hugging Face is a pioneering AI community dedicated to building the future of machine learning (ML).** Our platform serves as a collaborative space where researchers, developers, and organizations come together to share models, datasets, and applications. With over 400,000 models and 100,000 datasets, Hugging Face is the go-to hub for ML innovation.\n",
       "\n",
       "## Our Mission\n",
       "At Hugging Face, we aspire to accelerate ML research through collaboration and open-source tools. Our commitment to the community empowers creators worldwide to innovate and build cutting-edge AI solutions.\n",
       "\n",
       "## Key Offerings\n",
       "\n",
       "### Models & Datasets\n",
       "- **Explore 400k+ Models:** Access a diverse range of machine learning models, including state-of-the-art options for text, image, video, and audio processing.\n",
       "- **100k+ Datasets:** Leverage a rich library of datasets that cater to various ML tasks, or contribute your own to help expand the community's resources.\n",
       "\n",
       "### Spaces\n",
       "- Engage with more than 150k applications hosted on Hugging Face Spaces, providing users a platform to build and present their work efficiently. \n",
       "\n",
       "### Enterprise Solutions\n",
       "- **For Organizations:** Get dedicated support and advanced tools with our Enterprise plans, which offer features such as Single Sign-On, priority support, and secure access controls.\n",
       "\n",
       "## Who We Serve\n",
       "Hugging Face is trusted by more than 50,000 organizations, including tech giants like Amazon, Google, Microsoft, and Meta. Our diverse clientele ranges from non-profits to large corporations, all leveraging our tools for AI advancements.\n",
       "\n",
       "## Company Culture\n",
       "At Hugging Face, we celebrate a culture of openness and collaboration. We believe in harnessing the collective intelligence of the community to drive innovation in AI. Our team is passionate about:\n",
       "\n",
       "- **Open Source:** We foster an ecosystem where shared knowledge leads to groundbreaking technologies.\n",
       "- **Innovation:** Continuous learning and experimentation are at the heart of our work ethic. \n",
       "- **Inclusivity:** We are dedicated to creating an environment where every voice is heard and valued.\n",
       "\n",
       "## Careers at Hugging Face\n",
       "Join our growing team and help shape the future of AI! We are on the lookout for talented individuals across various domains, including but not limited to:\n",
       "\n",
       "- Machine Learning Engineering\n",
       "- Research & Development\n",
       "- Software Development\n",
       "- Community Management\n",
       "\n",
       "If you're passionate about AI and eager to make an impact, explore our [career opportunities](#) and become part of our mission!\n",
       "\n",
       "## Join Us Today!\n",
       "Discover the possibilities at Hugging Face and become a part of a vibrant community dedicated to pushing the boundaries of machine learning.\n",
       "\n",
       "- [Sign Up Now](#)\n",
       "- [Explore Our Models](#)\n",
       "- [Browse Datasets](#)\n",
       "- [Learn More About Our Solutions](#)\n",
       "\n",
       "**Hugging Face – The AI community building the future!**"
      ],
      "text/plain": [
       "<IPython.core.display.Markdown object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "stream_brochure(\"HuggingFace\", \"https://huggingface.co\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "fdb3f8d8-a3eb-41c8-b1aa-9f60686a653b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found links: {'links': [{'type': 'about page', 'url': 'https://huggingface.co'}, {'type': 'company page', 'url': 'https://huggingface.co/enterprise'}, {'type': 'pricing page', 'url': 'https://huggingface.co/pricing'}, {'type': 'careers page', 'url': 'https://apply.workable.com/huggingface/'}, {'type': 'blog page', 'url': 'https://huggingface.co/blog'}, {'type': 'community page', 'url': 'https://discuss.huggingface.co'}, {'type': 'github page', 'url': 'https://github.com/huggingface'}, {'type': 'linkedin page', 'url': 'https://www.linkedin.com/company/huggingface/'}, {'type': 'twitter page', 'url': 'https://twitter.com/huggingface'}]}\n"
     ]
    },
    {
     "data": {
      "text/markdown": [
       "# Hugging Face Brochure\n",
       "\n",
       "## Welcome to Hugging Face\n",
       "**The AI community building the future.**  \n",
       "Hugging Face is at the forefront of the machine learning revolution, providing a collaborative platform where enthusiasts, researchers, and developers work together on **models**, **datasets**, and **applications**.\n",
       "\n",
       "---\n",
       "\n",
       "## Our Offerings\n",
       "- **Models**: Over **400k** models available for various applications, including trending models such as **Llama-3.3** and **HunyuanVideo**.  \n",
       "- **Datasets**: Access to more than **100k datasets**, helping users find the right data to fuel their ML projects.  \n",
       "- **Spaces**: A creative playground with **150k+ applications** for testing and deploying ML projects.  \n",
       "\n",
       "### Accelerate Your ML Journey\n",
       "Boost your machine learning efforts using our **open-source stack**. Deploy on optimized inference endpoints or update applications in just a few clicks – starting at **$0.60/hour for GPU**.\n",
       "\n",
       "### Enterprise Solutions\n",
       "Hugging Face offers enterprise-grade solutions ideal for businesses including:\n",
       "- **Dedicated Support**\n",
       "- **Single Sign-On**\n",
       "- **Priority Access Controls**\n",
       "\n",
       "Plans start at **$20/user/month**.\n",
       "\n",
       "---\n",
       "\n",
       "## Company Culture\n",
       "At Hugging Face, we foster a culture of **collaboration and innovation**. We believe in:\n",
       "- **Open Source**: Building the ML tooling foundation with community input.\n",
       "- **Diversity and Inclusion**: Creating a welcoming and safe environment for every contributor.\n",
       "- **Continuous Learning**: Encouraging team members to share knowledge and grow their ML skills.\n",
       "\n",
       "---\n",
       "\n",
       "## Our Customers\n",
       "Join a community of over **50,000 organizations**, including top names like:\n",
       "- **AI at Meta**\n",
       "- **Amazon Web Services**\n",
       "- **Google**\n",
       "- **Microsoft**\n",
       "\n",
       "These companies trust Hugging Face to power their AI initiatives.\n",
       "\n",
       "---\n",
       "\n",
       "## Careers at Hugging Face\n",
       "Interested in joining our dynamic team? We offer a variety of positions for creative and driven individuals. Whether you're a developer, a data scientist, or an operations expert, if you're passionate about AI, we want to hear from you!  \n",
       "\n",
       "Check our **Jobs** page for current openings.\n",
       "\n",
       "---\n",
       "\n",
       "## Get Started Today!\n",
       "Become part of the future of AI at Hugging Face.  \n",
       "- **[Sign Up](https://huggingface.co/join)**  \n",
       "- **[Explore Our Models](https://huggingface.co/models)**  \n",
       "- **[Learn More About Our Services](https://huggingface.co/enterprise)**\n",
       "\n",
       "*Together, we’re building the future of AI with the power of collaboration.*"
      ],
      "text/plain": [
       "<IPython.core.display.Markdown object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Try changing the system prompt to the humorous version when you make the Brochure for Hugging Face:\n",
    "\n",
    "stream_brochure(\"HuggingFace\", \"https://huggingface.co\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
